/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bart.nl.client.nice;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author Bart Jansen
 */
public class CarPlusCar extends javax.swing.JPanel {

    private BufferedImage car;
    private int topLeftCarX = 0;
    private int topLeftCarY = 0;
    private AffineTransform at;
    private boolean firstTime = true;

    /**
     * Creates new form CarPlusCar
     */
    public CarPlusCar() {
        initComponents();
        if (!java.beans.Beans.isDesignTime()) {
            car = LoadImage("images//car.png");

        }

    }

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (java.beans.Beans.isDesignTime()) {
        } else if (firstTime) {
            firstTime = false;
            if (topLeftCarX == 0) {
                topLeftCarX = (this.getWidth() / 2) - (car.getWidth() / 2);
            }
            if (topLeftCarY == 0) {
                topLeftCarY = (this.getHeight() / 2) - (car.getHeight() / 2);
            }
            at = AffineTransform.getTranslateInstance(topLeftCarX, topLeftCarY);
        }

        Graphics2D g2d = (Graphics2D) g;
        g2d.drawImage(car, at, null);
    }

    private BufferedImage LoadImage(String FileName) {
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File(FileName));
        } catch (IOException e) {
            e.printStackTrace();
        }

        return img;
    }

    public void moveXY(int x, int y) {
        if (x != 0) {
            at.rotate(Math.toRadians(x), car.getWidth() / 2, car.getHeight() / 2);
            repaint();
        }

        if (y != 0) {
            at.translate(0, y);
            repaint();
        }

    }

    public void centreControl() {
        System.out.println("centre control");
    }

    
    public boolean carInCentre(){
        System.out.println(Math.atan2(at.getShearY(), at.getScaleY())); 
        return true;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(600, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
